<?php
/**
 * Tutoriales Lucio · CODLYX — catálogo de respaldo y whitelist de vistas
 * ---------------------------------------------------------------------
 * Este fichero cumple DOS funciones, ambas de seguridad o continuidad:
 *
 *  1. `views`   — WHITELIST. El campo `view_key` llega desde MySQL, es
 *                 decir, desde fuera del código. Jamás se concatena a una
 *                 ruta de fichero. Solo se acepta si es una clave EXACTA
 *                 de este array; el valor es el nombre de vista real.
 *                 Sin esto, un `view_key` como '../../config/config'
 *                 sería path traversal. Con esto, es simplemente inválido.
 *
 *  2. `tutorials` — CATÁLOGO DE RESPALDO. Si MySQL está deshabilitado,
 *                 mal configurado o caído, la biblioteca se sirve desde
 *                 aquí y el sitio sigue siendo navegable. Mantén esta
 *                 lista alineada con database/seed.sql.
 *
 * Al añadir un tutorial nuevo hay que tocar los DOS arrays. El README
 * lo explica paso a paso en «Agregar un nuevo tutorial».
 */

declare(strict_types=1);

return [

    /**
     * Whitelist  view_key => nombre de vista en app/Views/tutorials/<nombre>.php
     * La clave debe coincidir con tutorials.view_key en la base de datos.
     */
    'views' => [
        'wireshark' => 'wireshark',
        'nmap'      => 'nmap',
        'ssh'       => 'ssh',
    ],

    /**
     * Catálogo de respaldo. Mismos campos que devuelve la consulta SQL,
     * para que las vistas no distingan de dónde vienen los datos.
     */
    'tutorials' => [
        [
            'slug'        => 'wireshark',
            'name'        => 'Wireshark',
            'tagline'     => 'Análisis de paquetes y ciberseguridad defensiva',
            'description' => 'Curso completo en cinco partes: fundamentos de captura, los protocolos capa por capa (Ethernet, ARP, IPv4, IPv6, ICMP, TCP, UDP, DNS, DHCP, HTTP y TLS), las herramientas de Wireshark a fondo, análisis defensivo de tráfico y doce laboratorios prácticos con desafíos.',
            'icon'        => 'wireshark',
            'view_key'    => 'wireshark',
            'status'      => 'available',
            'category'    => 'Redes',
            'sort_order'  => 10,
        ],
        [
            'slug'        => 'nmap',
            'name'        => 'Nmap',
            'tagline'     => 'Descubrimiento de red y ciberseguridad defensiva',
            'description' => 'Curso completo en diez niveles: fundamentos y modelo mental, descubrimiento de hosts y CIDR, escaneo de puertos (TCP connect, SYN y UDP), detección de servicios y sistema operativo, el motor de scripts NSE con categorías seguras, resultados y reporting, ciberseguridad defensiva (superficie, hardening, validación de firewall y detección de escaneos), análisis avanzado y quince laboratorios prácticos sobre localhost y laboratorio propio.',
            'icon'        => 'nmap',
            'view_key'    => 'nmap',
            'status'      => 'available',
            'category'    => 'Redes',
            'sort_order'  => 15,
        ],
        [
            'slug'        => 'ssh',
            'name'        => 'SSH',
            'tagline'     => 'Acceso remoto seguro, administración y despliegues',
            'description' => 'Curso completo en diez partes: fundamentos (cliente y servidor, qué ocurre al conectar, huellas, host keys y known_hosts), trabajo en el servidor, autenticación con llaves y ssh-agent, el cliente a fondo (~/.ssh/config, debug, multiplexing), transferencia de archivos con scp, sftp y rsync, configuración y seguridad del servidor, túneles, ProxyJump y Git, despliegues profesionales, diagnóstico de errores y veinte ejercicios sobre un laboratorio propio.',
            'icon'        => 'ssh',
            'view_key'    => 'ssh',
            'status'      => 'available',
            'category'    => 'Sistemas',
            'sort_order'  => 20,
        ],
    ],

    /**
     * Índice de secciones de respaldo, por slug de tutorial.
     * Espejo de la tabla tutorial_sections.
     */
    'sections' => [
        'ssh' => [
            ['anchor' => 'que-es',               'label' => 'Qué es SSH',                         'badge' => '01', 'group' => 'Fundamentos'],
            ['anchor' => 'cliente-servidor',     'label' => 'ssh frente a sshd',                  'badge' => '02', 'group' => 'Fundamentos'],
            ['anchor' => 'puerto',               'label' => 'El puerto 22',                       'badge' => '03', 'group' => 'Fundamentos'],
            ['anchor' => 'anatomia',             'label' => 'Anatomía del comando',               'badge' => '04', 'group' => 'Fundamentos'],
            ['anchor' => 'flujo',                'label' => 'Qué ocurre al pulsar Enter',         'badge' => '05', 'group' => 'Fundamentos'],
            ['anchor' => 'primera',              'label' => 'Primera conexión',                   'badge' => '06', 'group' => 'Fundamentos'],
            ['anchor' => 'fingerprint',          'label' => 'La huella (fingerprint)',            'badge' => '07', 'group' => 'Fundamentos'],
            ['anchor' => 'host-key',             'label' => 'Host key y user key',                'badge' => '08', 'group' => 'Fundamentos'],
            ['anchor' => 'known-hosts',          'label' => 'known_hosts',                        'badge' => '09', 'group' => 'Fundamentos'],
            ['anchor' => 'host-cambiado',        'label' => 'Host key cambiada',                  'badge' => '10', 'group' => 'Fundamentos'],
            ['anchor' => 'practica-fundamentos', 'label' => 'Práctica: fundamentos',              'badge' => '11', 'group' => 'Fundamentos'],
            ['anchor' => 'navegar',              'label' => 'Navegar: pwd, ls, cd',               'badge' => '12', 'group' => 'En el servidor'],
            ['anchor' => 'rutas',                'label' => 'Rutas absolutas y relativas',        'badge' => '13', 'group' => 'En el servidor'],
            ['anchor' => 'ficheros',             'label' => 'mkdir, cp y mv',                     'badge' => '14', 'group' => 'En el servidor'],
            ['anchor' => 'rm',                   'label' => 'rm no tiene papelera',               'badge' => '15', 'group' => 'En el servidor'],
            ['anchor' => 'usuarios',             'label' => 'whoami, id y groups',                'badge' => '16', 'group' => 'En el servidor'],
            ['anchor' => 'root-sudo',            'label' => 'root y sudo',                        'badge' => '17', 'group' => 'En el servidor'],
            ['anchor' => 'permisos-linux',       'label' => 'Permisos Linux',                     'badge' => '18', 'group' => 'En el servidor'],
            ['anchor' => 'procesos',             'label' => 'Procesos: ps y top',                 'badge' => '19', 'group' => 'En el servidor'],
            ['anchor' => 'practica-linux',       'label' => 'Práctica: en el servidor',           'badge' => '20', 'group' => 'En el servidor'],
            ['anchor' => 'password-vs-llave',    'label' => 'Contraseña frente a llave',          'badge' => '21', 'group' => 'Llaves'],
            ['anchor' => 'llave-publica',        'label' => 'Llave pública y privada',            'badge' => '22', 'group' => 'Llaves'],
            ['anchor' => 'ssh-keygen',           'label' => 'ssh-keygen',                         'badge' => '23', 'group' => 'Llaves'],
            ['anchor' => 'passphrase',           'label' => 'La passphrase',                      'badge' => '24', 'group' => 'Llaves'],
            ['anchor' => 'ssh-copy-id',          'label' => 'ssh-copy-id',                        'badge' => '25', 'group' => 'Llaves'],
            ['anchor' => 'authorized-keys',      'label' => 'authorized_keys',                    'badge' => '26', 'group' => 'Llaves'],
            ['anchor' => 'permisos-ssh',         'label' => 'Permisos que exige OpenSSH',         'badge' => '27', 'group' => 'Llaves'],
            ['anchor' => 'ssh-agent',            'label' => 'ssh-agent y ssh-add',                'badge' => '28', 'group' => 'Llaves'],
            ['anchor' => 'practica-llaves',      'label' => 'Práctica: llaves',                   'badge' => '29', 'group' => 'Llaves'],
            ['anchor' => 'comandos-remotos',     'label' => 'Comandos remotos',                   'badge' => '30', 'group' => 'El cliente a fondo'],
            ['anchor' => 'quoting',              'label' => 'Comillas: local o remoto',           'badge' => '31', 'group' => 'El cliente a fondo'],
            ['anchor' => 'ssh-config',           'label' => '~/.ssh/config',                      'badge' => '32', 'group' => 'El cliente a fondo'],
            ['anchor' => 'config-progresiva',    'label' => 'Configuración progresiva',           'badge' => '33', 'group' => 'El cliente a fondo'],
            ['anchor' => 'wildcards',            'label' => 'Wildcards y precedencia',            'badge' => '34', 'group' => 'El cliente a fondo'],
            ['anchor' => 'debug',                'label' => 'Debug: -v, -vv, -vvv',               'badge' => '35', 'group' => 'El cliente a fondo'],
            ['anchor' => 'debug-real',           'label' => 'Leer un ssh -v real',                'badge' => '36', 'group' => 'El cliente a fondo'],
            ['anchor' => 'keepalive',            'label' => 'Keepalive',                          'badge' => '37', 'group' => 'El cliente a fondo'],
            ['anchor' => 'multiplexing',         'label' => 'Multiplexing',                       'badge' => '38', 'group' => 'El cliente a fondo'],
            ['anchor' => 'practica-cliente',     'label' => 'Práctica: el cliente',               'badge' => '39', 'group' => 'El cliente a fondo'],
            ['anchor' => 'transferir',           'label' => 'SSH, SCP, SFTP y rsync',             'badge' => '40', 'group' => 'Archivos'],
            ['anchor' => 'scp',                  'label' => 'SCP',                                'badge' => '41', 'group' => 'Archivos'],
            ['anchor' => 'sftp',                 'label' => 'SFTP',                               'badge' => '42', 'group' => 'Archivos'],
            ['anchor' => 'rsync',                'label' => 'rsync sobre SSH',                    'badge' => '43', 'group' => 'Archivos'],
            ['anchor' => 'rsync-barra',          'label' => 'La barra final de rsync',            'badge' => '44', 'group' => 'Archivos'],
            ['anchor' => 'dry-run',              'label' => '--dry-run',                          'badge' => '45', 'group' => 'Archivos'],
            ['anchor' => 'delete',               'label' => '--delete, con cuidado',              'badge' => '46', 'group' => 'Archivos'],
            ['anchor' => 'hosting',              'label' => 'SSH en hosting compartido',          'badge' => '47', 'group' => 'Archivos'],
            ['anchor' => 'practica-archivos',    'label' => 'Práctica: archivos',                 'badge' => '48', 'group' => 'Archivos'],
            ['anchor' => 'sshd',                 'label' => 'sshd y systemd',                     'badge' => '49', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'sshd-config',          'label' => 'sshd_config',                        'badge' => '50', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'config-vs-config',     'label' => 'ssh_config frente a sshd_config',    'badge' => '51', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'validar',              'label' => 'Validar con sshd -t',                'badge' => '52', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'reinicio-seguro',      'label' => 'Aplicar cambios sin quedarte fuera', 'badge' => '53', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'seguridad',            'label' => 'Seguridad por capas',                'badge' => '54', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'password-auth',        'label' => 'PasswordAuthentication',             'badge' => '55', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'root-login',           'label' => 'PermitRootLogin',                    'badge' => '56', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'logs',                 'label' => 'Logs de SSH',                        'badge' => '57', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'intentos',             'label' => 'Intentos fallidos',                  'badge' => '58', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'fail2ban',             'label' => 'Fail2Ban',                           'badge' => '59', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'practica-sshd',        'label' => 'Práctica: servidor',                 'badge' => '60', 'group' => 'Servidor y seguridad'],
            ['anchor' => 'tuneles',              'label' => 'Qué es un túnel',                    'badge' => '61', 'group' => 'Túneles y Git'],
            ['anchor' => 'local-forward',        'label' => 'Local forwarding (-L)',              'badge' => '62', 'group' => 'Túneles y Git'],
            ['anchor' => 'remote-forward',       'label' => 'Remote forwarding (-R)',             'badge' => '63', 'group' => 'Túneles y Git'],
            ['anchor' => 'dynamic-forward',      'label' => 'Dynamic forwarding (-D)',            'badge' => '64', 'group' => 'Túneles y Git'],
            ['anchor' => 'comparar-tuneles',     'label' => '-L frente a -R frente a -D',         'badge' => '65', 'group' => 'Túneles y Git'],
            ['anchor' => 'proxyjump',            'label' => 'ProxyJump y bastión',                'badge' => '66', 'group' => 'Túneles y Git'],
            ['anchor' => 'git-ssh',              'label' => 'Git sobre SSH',                      'badge' => '67', 'group' => 'Túneles y Git'],
            ['anchor' => 'practica-tuneles',     'label' => 'Práctica: túneles y Git',            'badge' => '68', 'group' => 'Túneles y Git'],
            ['anchor' => 'deploy-niveles',       'label' => 'Seis niveles de despliegue',         'badge' => '69', 'group' => 'Despliegues'],
            ['anchor' => 'deploy-rsync',         'label' => 'Deploy con rsync',                   'badge' => '70', 'group' => 'Despliegues'],
            ['anchor' => 'no-subir',             'label' => 'Lo que no se sube',                  'badge' => '71', 'group' => 'Despliegues'],
            ['anchor' => 'backup',               'label' => 'Backup antes de desplegar',          'badge' => '72', 'group' => 'Despliegues'],
            ['anchor' => 'atomico',              'label' => 'Deploy atómico',                     'badge' => '73', 'group' => 'Despliegues'],
            ['anchor' => 'automatizar',          'label' => 'Script de despliegue',               'badge' => '74', 'group' => 'Despliegues'],
            ['anchor' => 'scripts-seguros',      'label' => 'SSH en scripts',                     'badge' => '75', 'group' => 'Despliegues'],
            ['anchor' => 'practica-deploy',      'label' => 'Práctica: despliegue',               'badge' => '76', 'group' => 'Despliegues'],
            ['anchor' => 'arbol',                'label' => 'Árbol de diagnóstico',               'badge' => '77', 'group' => 'Diagnóstico'],
            ['anchor' => 'refused',              'label' => 'Connection refused',                 'badge' => '78', 'group' => 'Diagnóstico'],
            ['anchor' => 'timeout',              'label' => 'Timed out y No route',               'badge' => '79', 'group' => 'Diagnóstico'],
            ['anchor' => 'resolve',              'label' => 'Could not resolve hostname',         'badge' => '80', 'group' => 'Diagnóstico'],
            ['anchor' => 'publickey',            'label' => 'Permission denied (publickey)',      'badge' => '81', 'group' => 'Diagnóstico'],
            ['anchor' => 'too-many',             'label' => 'Too many authentication failures',   'badge' => '82', 'group' => 'Diagnóstico'],
            ['anchor' => 'hostkey-failed',       'label' => 'Host key verification failed',       'badge' => '83', 'group' => 'Diagnóstico'],
            ['anchor' => 'dos-lados',            'label' => 'Cliente y servidor a la vez',        'badge' => '84', 'group' => 'Diagnóstico'],
            ['anchor' => 'practica-diagnostico', 'label' => 'Práctica: diagnóstico',              'badge' => '85', 'group' => 'Diagnóstico'],
            ['anchor' => 'decision',             'label' => '¿Qué herramienta uso?',              'badge' => '86', 'group' => 'Referencia'],
            ['anchor' => 'chuleta',              'label' => 'Chuleta de SSH',                     'badge' => '87', 'group' => 'Referencia'],
            ['anchor' => 'glosario',             'label' => 'Glosario',                           'badge' => '88', 'group' => 'Referencia'],
        ],

        'nmap' => [
            ['anchor' => 'que-es',          'label' => 'Qué es Nmap',                  'badge' => '01', 'group' => 'Fundamentos'],
            ['anchor' => 'alcance',         'label' => 'Autorización y alcance',       'badge' => '02', 'group' => 'Fundamentos'],
            ['anchor' => 'modelo',          'label' => 'El modelo mental',              'badge' => '03', 'group' => 'Fundamentos'],
            ['anchor' => 'instalar',        'label' => 'Instalar y validar',            'badge' => '04', 'group' => 'Fundamentos'],
            ['anchor' => 'privilegios',     'label' => 'Privilegios: sudo',             'badge' => '05', 'group' => 'Fundamentos'],
            ['anchor' => 'tcp-udp',         'label' => 'TCP y UDP',                     'badge' => '06', 'group' => 'Fundamentos'],
            ['anchor' => 'primer',          'label' => 'Primer escaneo',                'badge' => '07', 'group' => 'Fundamentos'],
            ['anchor' => 'salida',          'label' => 'Anatomía de la salida',        'badge' => '08', 'group' => 'Fundamentos'],
            ['anchor' => 'estados',         'label' => 'Estados de puerto',             'badge' => '09', 'group' => 'Fundamentos'],
            ['anchor' => 'cidr',            'label' => 'CIDR',                          'badge' => '10', 'group' => 'Descubrimiento'],
            ['anchor' => 'mi-red',          'label' => 'Identificar tu red',            'badge' => '11', 'group' => 'Descubrimiento'],
            ['anchor' => 'objetivos',       'label' => 'Especificar objetivos',         'badge' => '12', 'group' => 'Descubrimiento'],
            ['anchor' => 'list-scan',       'label' => 'List scan (-sL)',               'badge' => '13', 'group' => 'Descubrimiento'],
            ['anchor' => 'descubrimiento',  'label' => 'Host discovery (-sn)',          'badge' => '14', 'group' => 'Descubrimiento'],
            ['anchor' => 'pn',              'label' => 'Omitir descubrimiento (-Pn)',   'badge' => '15', 'group' => 'Descubrimiento'],
            ['anchor' => 'dns',             'label' => 'DNS y nombres',                 'badge' => '16', 'group' => 'Descubrimiento'],
            ['anchor' => 'puertos',         'label' => 'Seleccionar puertos (-p)',      'badge' => '17', 'group' => 'Puertos'],
            ['anchor' => 'comunes',         'label' => 'Puertos comunes',               'badge' => '18', 'group' => 'Puertos'],
            ['anchor' => 'connect',         'label' => 'TCP connect (-sT)',             'badge' => '19', 'group' => 'Puertos'],
            ['anchor' => 'syn',             'label' => 'SYN scan (-sS)',                'badge' => '20', 'group' => 'Puertos'],
            ['anchor' => 'st-vs-ss',        'label' => '-sT frente a -sS',              'badge' => '21', 'group' => 'Puertos'],
            ['anchor' => 'udp',             'label' => 'Escaneo UDP (-sU)',             'badge' => '22', 'group' => 'Puertos'],
            ['anchor' => 'combinado',       'label' => 'TCP y UDP juntos',              'badge' => '23', 'group' => 'Puertos'],
            ['anchor' => 'razones',         'label' => 'Verbosidad y razones',          'badge' => '24', 'group' => 'Puertos'],
            ['anchor' => 'versiones',       'label' => 'Servicios y versiones (-sV)',   'badge' => '25', 'group' => 'Servicios'],
            ['anchor' => 'importa-version', 'label' => '¿Por qué importa la versión?', 'badge' => '26', 'group' => 'Servicios'],
            ['anchor' => 'os',              'label' => 'Detección de SO (-O)',         'badge' => '27', 'group' => 'Sistema operativo'],
            ['anchor' => 'traceroute',      'label' => 'Camino al objetivo',            'badge' => '28', 'group' => 'Sistema operativo'],
            ['anchor' => 'agresivo',        'label' => 'La opción -A',                 'badge' => '29', 'group' => 'Sistema operativo'],
            ['anchor' => 'timing',          'label' => 'Timing (-T0 a -T5)',            'badge' => '30', 'group' => 'Sistema operativo'],
            ['anchor' => 'fuera-alcance',   'label' => 'Fuera de alcance',              'badge' => '31', 'group' => 'Sistema operativo'],
            ['anchor' => 'nse',             'label' => 'Qué es NSE',                   'badge' => '32', 'group' => 'NSE'],
            ['anchor' => 'nse-categorias',  'label' => 'Categorías NSE',               'badge' => '33', 'group' => 'NSE'],
            ['anchor' => 'script-help',     'label' => '--script-help',                 'badge' => '34', 'group' => 'NSE'],
            ['anchor' => 'nse-seguros',     'label' => 'Scripts seguros',               'badge' => '35', 'group' => 'NSE'],
            ['anchor' => 'nse-http',        'label' => 'NSE sobre HTTP',                'badge' => '36', 'group' => 'NSE'],
            ['anchor' => 'nse-tls',         'label' => 'NSE sobre TLS',                 'badge' => '37', 'group' => 'NSE'],
            ['anchor' => 'nse-info',        'label' => 'NSE: SSH y DNS',                'badge' => '38', 'group' => 'NSE'],
            ['anchor' => 'guardar',         'label' => 'Guardar resultados',            'badge' => '39', 'group' => 'Resultados'],
            ['anchor' => 'formatos',        'label' => '¿Qué formato usar?',          'badge' => '40', 'group' => 'Resultados'],
            ['anchor' => 'comparar',        'label' => 'Comparar escaneos',             'badge' => '41', 'group' => 'Resultados'],
            ['anchor' => 'inventario',      'label' => 'Inventario de red',             'badge' => '42', 'group' => 'Resultados'],
            ['anchor' => 'superficie',      'label' => 'Superficie de ataque',          'badge' => '43', 'group' => 'Ciberseguridad'],
            ['anchor' => 'inesperados',     'label' => 'Servicios inesperados',         'badge' => '44', 'group' => 'Ciberseguridad'],
            ['anchor' => 'hardening',       'label' => 'Inventario y hardening',        'badge' => '45', 'group' => 'Ciberseguridad'],
            ['anchor' => 'firewall',        'label' => 'Validar un firewall',           'badge' => '46', 'group' => 'Ciberseguridad'],
            ['anchor' => 'deteccion',       'label' => 'Detectar escaneos',             'badge' => '47', 'group' => 'Ciberseguridad'],
            ['anchor' => 'wireshark',       'label' => 'Nmap + Wireshark',              'badge' => '48', 'group' => 'Ciberseguridad'],
            ['anchor' => 'limitaciones',    'label' => 'Falsos positivos',              'badge' => '49', 'group' => 'Análisis avanzado'],
            ['anchor' => 'errores',         'label' => 'Errores comunes',               'badge' => '50', 'group' => 'Análisis avanzado'],
            ['anchor' => 'metodologia',     'label' => 'Árbol de decisión',           'badge' => '51', 'group' => 'Análisis avanzado'],
            ['anchor' => 'auditoria',       'label' => 'Flujo de auditoría',           'badge' => '52', 'group' => 'Análisis avanzado'],
            ['anchor' => 'informe',         'label' => 'Mini informe',                  'badge' => '53', 'group' => 'Análisis avanzado'],
            ['anchor' => 'hecho-hipotesis', 'label' => 'Hechos vs hipótesis',          'badge' => '54', 'group' => 'Análisis avanzado'],
            ['anchor' => 'labs',            'label' => '15 laboratorios',               'badge' => '55', 'group' => 'Práctica'],
            ['anchor' => 'desafios',        'label' => 'Desafíos',                     'badge' => '56', 'group' => 'Práctica'],
            ['anchor' => 'chuleta',         'label' => 'Chuleta de Nmap',               'badge' => '57', 'group' => 'Práctica'],
        ],

        'wireshark' => [
            ['anchor' => 'que-es',           'label' => 'Qué es Wireshark',        'badge' => '01', 'group' => 'Fundamentos'],
            ['anchor' => 'instalar',         'label' => 'Instalar y permisos',     'badge' => '02', 'group' => 'Fundamentos'],
            ['anchor' => 'interfaz',         'label' => 'La interfaz por dentro',  'badge' => '03', 'group' => 'Fundamentos'],
            ['anchor' => 'ventana',          'label' => 'Los tres paneles',        'badge' => '04', 'group' => 'Fundamentos'],
            ['anchor' => 'mental',           'label' => 'Encapsulación y capas',   'badge' => '05', 'group' => 'Fundamentos'],
            ['anchor' => 'filtros',          'label' => 'Captura vs. visualización', 'badge' => '06', 'group' => 'Fundamentos'],
            ['anchor' => 'display-filters',  'label' => 'Lenguaje de filtros',     'badge' => '07', 'group' => 'Fundamentos'],
            ['anchor' => 'ethernet',         'label' => 'Ethernet',                'badge' => '08', 'group' => 'Protocolos'],
            ['anchor' => 'arp',              'label' => 'ARP',                     'badge' => '09', 'group' => 'Protocolos'],
            ['anchor' => 'ipv4',             'label' => 'IPv4',                    'badge' => '10', 'group' => 'Protocolos'],
            ['anchor' => 'ipv6',             'label' => 'IPv6',                    'badge' => '11', 'group' => 'Protocolos'],
            ['anchor' => 'icmp',             'label' => 'ICMP',                    'badge' => '12', 'group' => 'Protocolos'],
            ['anchor' => 'tcp',              'label' => 'TCP',                     'badge' => '13', 'group' => 'Protocolos'],
            ['anchor' => 'udp',              'label' => 'UDP',                     'badge' => '14', 'group' => 'Protocolos'],
            ['anchor' => 'dns',              'label' => 'DNS',                     'badge' => '15', 'group' => 'Protocolos'],
            ['anchor' => 'dhcp',             'label' => 'DHCP',                    'badge' => '16', 'group' => 'Protocolos'],
            ['anchor' => 'http',             'label' => 'HTTP',                    'badge' => '17', 'group' => 'Protocolos'],
            ['anchor' => 'tls',              'label' => 'HTTPS y TLS',             'badge' => '18', 'group' => 'Protocolos'],
            ['anchor' => 'follow',           'label' => 'Follow Stream',           'badge' => '19', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'statistics',       'label' => 'Statistics',              'badge' => '20', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'expert',           'label' => 'Expert Information',      'badge' => '21', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'coloring',         'label' => 'Coloring rules',          'badge' => '22', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'columnas',         'label' => 'Columnas propias',        'badge' => '23', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'perfiles',         'label' => 'Perfiles',                'badge' => '24', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'tls-descifrado',   'label' => 'Descifrar TLS propio',    'badge' => '25', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'tshark',           'label' => 'tshark',                  'badge' => '26', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'pcap',             'label' => 'PCAP y su custodia',      'badge' => '27', 'group' => 'Wireshark a fondo'],
            ['anchor' => 'ciber',            'label' => 'Análisis defensivo',      'badge' => '28', 'group' => 'Ciberseguridad'],
            ['anchor' => 'baseline',         'label' => 'Línea base',              'badge' => '29', 'group' => 'Ciberseguridad'],
            ['anchor' => 'scan',             'label' => 'Escaneo de puertos',      'badge' => '30', 'group' => 'Ciberseguridad'],
            ['anchor' => 'beaconing',        'label' => 'Beaconing',               'badge' => '31', 'group' => 'Ciberseguridad'],
            ['anchor' => 'dns-raro',         'label' => 'DNS sospechoso',          'badge' => '32', 'group' => 'Ciberseguridad'],
            ['anchor' => 'arp-raro',         'label' => 'ARP anómalo',             'badge' => '33', 'group' => 'Ciberseguridad'],
            ['anchor' => 'exfil',            'label' => 'Exfiltración',            'badge' => '34', 'group' => 'Ciberseguridad'],
            ['anchor' => 'http-raro',        'label' => 'HTTP sospechoso',         'badge' => '35', 'group' => 'Ciberseguridad'],
            ['anchor' => 'claro',            'label' => 'Credenciales en claro',   'badge' => '36', 'group' => 'Ciberseguridad'],
            ['anchor' => 'resets',           'label' => 'Resets y pérdidas',       'badge' => '37', 'group' => 'Ciberseguridad'],
            ['anchor' => 'flujo',            'label' => 'Flujo de análisis',       'badge' => '38', 'group' => 'Ciberseguridad'],
            ['anchor' => 'informe',          'label' => 'Informe de incidente',    'badge' => '39', 'group' => 'Ciberseguridad'],
            ['anchor' => 'labs',             'label' => '12 laboratorios',         'badge' => '40', 'group' => 'Práctica'],
            ['anchor' => 'desafios',         'label' => 'Desafíos',                'badge' => '41', 'group' => 'Práctica'],
            ['anchor' => 'errores',          'label' => 'Errores comunes',         'badge' => '42', 'group' => 'Práctica'],
            ['anchor' => 'chuleta',          'label' => 'Chuleta de filtros',      'badge' => '43', 'group' => 'Práctica'],
        ],
    ],
];
