// Banco de preguntas tipo examen de VLAN (niveles 1 a 3, los que entran en el CCST).
import { op, vs, rel, ord } from './_ayuda.mjs';

const VLAN_BRIEF = `Switch# show vlan brief

VLAN Name                 Status    Ports
---- -------------------- --------- -----------------------------
1    default              active    Fa0/7, Fa0/8, Gi0/2
10   VENTAS               active    Fa0/1, Fa0/2, Fa0/3
20   SOPORTE              active    Fa0/4, Fa0/5
30   DIRECCION            active    Fa0/6`;

export default {
  1: [
    op('¿Qué problema resuelve principalmente una VLAN?', ['Aumenta la velocidad de los puertos', 'Divide un switch en varios dominios de broadcast', 'Asigna direcciones IP a los equipos', 'Cifra el tráfico entre equipos'], 1, 'Una VLAN es un dominio de broadcast independiente creado por configuración. No cambia la velocidad, no reparte direcciones (eso es DHCP) y no cifra.'),
    op('Dos computadoras están en el mismo switch, una en la VLAN 10 y otra en la VLAN 20, y no se hacen ping. Las direcciones IP son correctas. ¿Qué falta?', ['Un cable cruzado entre ellas', 'Un router o switch de capa 3 que enrute entre las VLAN', 'Activar el puerto con no shutdown', 'Poner las dos en modo troncal'], 1, 'Un switch de capa 2 nunca pasa tramas de una VLAN a otra. Para comunicarlas hace falta un dispositivo de capa 3.'),
    op('¿En qué VLAN están todos los puertos de un switch Cisco recién sacado de la caja?', ['VLAN 0', 'VLAN 1', 'VLAN 99', 'En ninguna'], 1, 'La VLAN 1 es la VLAN por defecto: existe siempre y contiene todos los puertos hasta que se asignan a otra.'),
    op('Según la salida, ¿cuántos puertos de acceso tiene la VLAN 10?', ['2', '3', '5', '8'], 1, 'La fila de la VLAN 10 lista Fa0/1, Fa0/2 y Fa0/3: tres puertos.', { codigo: VLAN_BRIEF }),
    op('Según la salida, un equipo conectado a Fa0/5 envía un broadcast. ¿Por qué otro puerto de acceso sale?', ['Fa0/4', 'Fa0/6', 'Fa0/1', 'Por todos los puertos'], 0, 'Fa0/5 pertenece a la VLAN 20, y el único otro puerto de esa VLAN es Fa0/4. El broadcast no cruza a otras VLAN.', { codigo: VLAN_BRIEF }),
    op('El puerto Gi0/1 de ese switch no aparece en la salida de `show vlan brief`. ¿Cuál es la explicación más probable?', ['Está averiado', 'Es un puerto troncal', 'Está en la VLAN 0', 'Le falta dirección IP'], 1, '`show vlan brief` solo lista puertos de acceso. Los troncales transportan varias VLAN y se consultan con `show interfaces trunk`.', { codigo: VLAN_BRIEF }),
    op('¿Qué comando asigna un puerto de acceso a la VLAN 30?', ['`vlan 30`', '`switchport access vlan 30`', '`switchport mode trunk`', '`name 30`'], 1, '`switchport access vlan 30`, dentro de la interfaz. `vlan 30` solo crea la VLAN y `name` le pone nombre.'),
    op('¿Cuántas subredes IP necesita como mínimo una red con las VLAN 10, 20, 30 y 40?', ['Una', 'Dos', 'Cuatro', 'Ocho'], 2, 'Cada VLAN es una red aparte y necesita su propia subred: una VLAN, una subred.'),
    op('¿Qué decide a qué VLAN pertenece una computadora conectada por cable?', ['Su dirección IP', 'La configuración del puerto del switch donde se conecta', 'Su sistema operativo', 'El nombre del equipo'], 1, 'La VLAN se asigna al puerto del switch. Si mueves el equipo a un puerto de otra VLAN, cambia de red.'),
    op('¿Qué rango de ID es el «rango normal» de VLAN que se crea y se borra libremente?', ['0 a 4095', '2 a 1001', '1002 a 1005', '1006 a 4094'], 1, 'Del 2 al 1001. La 1 no se puede borrar, de la 1002 a la 1005 están reservadas y de la 1006 a la 4094 es el rango extendido.'),
    vs('¿Qué dos beneficios aporta dividir una red en VLAN?', ['Dominios de broadcast más pequeños', 'Separar departamentos sin comprar más switches', 'Más ancho de banda por puerto', 'Eliminar la necesidad de direcciones IP'], [0, 1], 'Las VLAN reducen el alcance de los broadcast y aíslan grupos por configuración. No cambian la velocidad del puerto ni sustituyen al direccionamiento.'),
    vs('¿Qué dos comandos se escriben dentro de una interfaz para dejarla como puerto de acceso en la VLAN 20?', ['`switchport mode access`', '`switchport access vlan 20`', '`switchport mode trunk`', '`vlan 20`', '`show vlan brief`'], [0, 1], 'Uno fija el modo y el otro la VLAN. `vlan 20` va en configuración global y `show` solo consulta.'),
    rel('Relaciona cada tipo de VLAN con su uso.', [['De datos', 'Tráfico normal de los usuarios'], ['De voz', 'Teléfonos IP, con prioridad'], ['De gestión', 'Acceso de los administradores a los switches'], ['Nativa', 'Tramas sin etiqueta en un troncal']], 'Cada tipo separa un tráfico con necesidades distintas: rendimiento para la voz, aislamiento para la gestión y compatibilidad para la nativa.'),
    ord('Ordena los pasos para poner un puerto en una VLAN nueva.', ['Entrar en configuración global', 'Crear la VLAN y ponerle nombre', 'Entrar en la interfaz', 'Fijar el modo acceso', 'Asignar la VLAN al puerto'], 'Primero existe la VLAN y después se le asignan puertos. Si se asigna antes, el switch crea la VLAN solo, pero sin nombre.'),
  ],
  2: [
    op('¿Qué es un enlace troncal?', ['Un puerto que pertenece a una sola VLAN', 'Un enlace que transporta tramas de varias VLAN a la vez', 'Un cable de fibra entre dos edificios', 'Un puerto apagado por seguridad'], 1, 'El troncal lleva varias VLAN por un mismo enlace, normalmente entre switches o hacia un router. Para distinguirlas, etiqueta las tramas.'),
    op('¿Qué estándar define la etiqueta de VLAN en un troncal?', ['IEEE 802.3', 'IEEE 802.1Q', 'IEEE 802.11', 'IEEE 802.1X'], 1, '802.1Q añade una etiqueta de 4 bytes con el ID de VLAN. 802.3 es Ethernet, 802.11 es Wi-Fi y 802.1X es control de acceso.'),
    op('¿Cuántos bits tiene el campo de ID de VLAN en la etiqueta 802.1Q?', ['8', '12', '16', '32'], 1, '12 bits dan 4,096 valores (0 a 4095), de los que se usan del 1 al 4094.'),
    op('¿Cómo viajan por un troncal las tramas de la VLAN nativa?', ['Con doble etiqueta', 'Sin etiqueta', 'Cifradas', 'No pueden viajar'], 1, 'La VLAN nativa es la única cuyas tramas cruzan el troncal sin etiquetar. Por eso debe coincidir en los dos extremos.'),
    op('Dos switches están unidos por un troncal. Los equipos de la VLAN 10 se comunican entre switches, pero los de la VLAN 20 no. ¿Qué revisarías primero?', ['Que la VLAN 20 esté creada en los dos switches y permitida en el troncal', 'La velocidad del troncal', 'La dirección MAC de los equipos', 'El servidor DNS'], 0, 'Si una VLAN funciona y otra no por el mismo enlace, el cable está bien. Lo habitual es que la VLAN 20 no exista en un switch o no esté en la lista de permitidas.'),
    op('¿Qué comando muestra los troncales, su VLAN nativa y las VLAN permitidas?', ['`show vlan brief`', '`show interfaces trunk`', '`show ip route`', '`show version`'], 1, '`show interfaces trunk`. `show vlan brief` solo lista los puertos de acceso de cada VLAN.'),
    op('Un técnico escribe `switchport trunk allowed vlan 30` en un troncal que ya permitía las VLAN 10 y 20. ¿Qué ocurre?', ['Se permiten 10, 20 y 30', 'Solo queda permitida la 30', 'El comando da error', 'Se borra la VLAN 30'], 1, 'Sin la palabra `add`, el comando sustituye toda la lista. Para añadir se usa `switchport trunk allowed vlan add 30`.'),
    op('Una trama de la VLAN 20 sale hacia una computadora por un puerto de acceso. ¿Lleva etiqueta?', ['Sí, con el ID 20', 'No: el switch la quita antes de entregarla', 'Sí, con el ID 1', 'Depende del sistema operativo'], 1, 'Los equipos finales esperan tramas Ethernet normales. La etiqueta solo existe en los troncales.'),
    op('¿Qué comando fija una interfaz como troncal?', ['`switchport mode access`', '`switchport mode trunk`', '`switchport trunk native vlan 1`', '`encapsulation dot1q 1`'], 1, '`switchport mode trunk`. El de la VLAN nativa solo cambia cuál viaja sin etiqueta, y `encapsulation dot1q` es de subinterfaces de router.'),
    op('¿Por qué se recomienda cambiar la VLAN nativa a una que no se use para usuarios?', ['Para ganar velocidad', 'Para reducir el riesgo de ataques que aprovechan las tramas sin etiqueta', 'Porque la VLAN 1 no admite troncales', 'Para ahorrar direcciones IP'], 1, 'Las tramas sin etiqueta son el punto débil del troncal (por ejemplo, el salto de VLAN con doble etiqueta). Usar una VLAN nativa sin equipos limita el daño.'),
    vs('¿Qué dos condiciones deben coincidir en los dos extremos de un troncal?', ['La VLAN nativa', 'El modo troncal y el etiquetado 802.1Q', 'El nombre del switch', 'La dirección IP de gestión'], [0, 1], 'Los dos lados deben ser troncales con 802.1Q y con la misma VLAN nativa. El nombre y la IP de gestión no influyen en el enlace.'),
    vs('¿En qué dos tipos de enlace se usa normalmente un troncal?', ['Entre dos switches', 'Entre un switch y un router que enruta varias VLAN', 'Entre un switch y una impresora', 'Entre un switch y una computadora de escritorio'], [0, 1], 'El troncal hace falta donde un solo cable debe llevar varias VLAN. Una impresora o una computadora pertenecen a una sola VLAN: puerto de acceso.'),
    rel('Relaciona cada comando con lo que hace.', [['`switchport mode trunk`', 'Convierte el puerto en troncal'], ['`switchport trunk native vlan 99`', 'Cambia la VLAN que viaja sin etiqueta'], ['`switchport trunk allowed vlan 10,20`', 'Limita las VLAN que cruzan el troncal'], ['`switchport nonegotiate`', 'Desactiva la negociación automática DTP']], 'Los cuatro se escriben dentro de la interfaz troncal.'),
    ord('Ordena lo que ocurre cuando una trama de la VLAN 10 viaja de una PC en SW1 a otra en SW2.', ['La PC envía una trama Ethernet normal', 'SW1 la recibe por un puerto de acceso de la VLAN 10', 'SW1 le añade la etiqueta 802.1Q con el ID 10 y la envía por el troncal', 'SW2 lee la etiqueta y busca el destino en la VLAN 10', 'SW2 quita la etiqueta y entrega la trama por el puerto de acceso'], 'La etiqueta solo vive en el troncal: se pone al entrar en él y se quita antes de llegar al equipo final.'),
  ],
  3: [
    op('PC-A (SW1, VLAN 10) y PC-B (SW2, VLAN 10) no se comunican. El troncal entre los switches solo permite las VLAN 20 y 30. ¿Cuál es la causa?', ['Están en VLAN distintas', 'La VLAN 10 no está permitida en el troncal', 'Falta un router', 'El troncal usa una VLAN nativa'], 1, 'Comparten VLAN, así que no hace falta router. Pero la trama debe cruzar el troncal y la VLAN 10 no está en la lista: el switch la descarta.'),
    op('Un usuario cambia su computadora de escritorio a otra mesa y deja de tener red. Su IP es fija. ¿Qué es lo más probable?', ['El cable nuevo es de fibra', 'El puerto nuevo pertenece a otra VLAN y su IP ya no corresponde a esa red', 'La dirección MAC cambió', 'El switch se quedó sin direcciones'], 1, 'La VLAN depende del puerto. Con una IP fija de la red anterior, el equipo queda en una subred que no coincide con la de la VLAN nueva.'),
    op('Tras borrar la VLAN 20 con `no vlan 20`, los equipos de sus puertos dejan de funcionar. ¿Por qué?', ['Los puertos pasaron a la VLAN 1 con otra subred', 'Los puertos quedaron asignados a una VLAN que ya no existe y están inactivos', 'El switch se reinició', 'Se borró la tabla de direcciones MAC para siempre'], 1, 'Los puertos no vuelven solos a la VLAN 1: siguen apuntando a la 20, que ya no existe, y quedan inactivos hasta que se les asigna otra VLAN o se vuelve a crear.'),
    op('En un switch con las VLAN 10, 20 y 30 en uso, ¿cuántos dominios de broadcast hay?', ['1', '3', 'Uno por puerto', 'Depende del número de troncales'], 1, 'Cada VLAN en uso es un dominio de broadcast. Los troncales no añaden dominios: solo transportan los que ya existen.'),
    op('Un switch muestra el aviso de CDP «Native VLAN mismatch» en un troncal. ¿Qué significa?', ['Que las listas de VLAN permitidas no coinciden', 'Que cada extremo tiene configurada una VLAN nativa distinta', 'Que el cable está dañado', 'Que el troncal está apagado'], 1, 'El aviso indica que las VLAN nativas no coinciden. Las tramas sin etiqueta de un lado acaban en otra VLAN en el otro: se mezclan dos redes.'),
    op('Un teléfono IP y una computadora comparten un mismo puerto del switch. ¿Cómo se separa su tráfico?', ['Con dos cables', 'Con una VLAN de datos y una VLAN de voz en el mismo puerto de acceso', 'Con un troncal sin restricciones', 'No se puede separar'], 1, 'El puerto sigue siendo de acceso para la computadora y se le añade una VLAN de voz para el teléfono con `switchport voice vlan`.'),
    op('PC-A está en la VLAN 10 de SW1 y PC-B en la VLAN 20 de SW2. El troncal permite todas las VLAN y no hay router. ¿Se comunican?', ['Sí, por el troncal', 'No: son VLAN distintas y no hay enrutamiento', 'Sí, si tienen la misma máscara', 'Solo si la VLAN nativa es la 10'], 1, 'El troncal transporta las dos VLAN, pero no las mezcla. Sin un router o switch de capa 3, dos VLAN distintas no se alcanzan.'),
    op('¿Qué comando conviene ejecutar primero para comprobar a qué VLAN pertenece el puerto de un usuario?', ['`show vlan brief`', '`show ip route`', '`show version`', '`show inventory`'], 0, '`show vlan brief` lista cada VLAN con sus puertos de acceso: se ve de un vistazo dónde está el puerto.'),
    op('Tres switches están en línea: SW1–SW2–SW3. El troncal SW1–SW2 permite 10 y 20; el SW2–SW3 solo permite 10. Una PC de la VLAN 20 en SW1 quiere llegar a otra de la VLAN 20 en SW3. ¿Lo consigue?', ['Sí', 'No: el segundo troncal no permite la VLAN 20', 'Sí, pero más lento', 'Solo los broadcast'], 1, 'La trama cruza el primer troncal, pero SW2 la descarta al intentar enviarla por el segundo, que no admite la VLAN 20.'),
    op('¿Por qué se recomienda no usar la VLAN 1 para los usuarios?', ['Porque es más lenta', 'Porque todo puerto sin configurar pertenece a ella y daría acceso a esa red', 'Porque no admite direcciones IP', 'Porque no cruza los troncales'], 1, 'Como todos los puertos nacen en la VLAN 1, cualquier puerto olvidado sería una entrada a la red de usuarios o de gestión.'),
    vs('¿Qué dos acciones mejoran la seguridad de los puertos sin uso de un switch?', ['Apagarlos con shutdown', 'Asignarlos a una VLAN sin uso', 'Convertirlos en troncales', 'Dejarlos en la VLAN 1'], [0, 1], 'Un puerto apagado y en una VLAN «estacionamiento» no da acceso a nada. Un troncal abierto o la VLAN 1 son justo lo contrario.'),
    vs('Una PC de la VLAN 30 no se comunica con otra de la VLAN 30 en un switch vecino. ¿Qué dos causas son posibles?', ['La VLAN 30 no está creada en el switch vecino', 'La VLAN 30 no está permitida en el troncal', 'No hay router entre los switches', 'Las PC usan sistemas operativos distintos'], [0, 1], 'Dentro de una misma VLAN no interviene ningún router. Los fallos típicos son que la VLAN no exista en un switch o que el troncal no la deje pasar.'),
    rel('Relaciona cada síntoma con su causa más probable.', [['Una sola VLAN no cruza entre switches', 'VLAN no permitida en el troncal'], ['Aviso «Native VLAN mismatch»', 'VLAN nativa distinta en cada extremo'], ['Puertos inactivos tras un cambio', 'Se borró la VLAN a la que pertenecían'], ['Ningún equipo cruza entre switches', 'El enlace no está en modo troncal']], 'Cada síntoma apunta a una parte distinta de la configuración: la lista de permitidas, la nativa, la base de VLAN o el modo del enlace.'),
    ord('Ordena el diagnóstico de un equipo que no alcanza a otro de su misma VLAN en otro switch.', ['Comprobar que el puerto del equipo esté en la VLAN correcta', 'Comprobar que la VLAN exista en los dos switches', 'Comprobar que el enlace entre switches sea troncal', 'Comprobar que la VLAN esté permitida en el troncal', 'Comprobar que la VLAN nativa coincida en los dos extremos'], 'Se sigue el camino de la trama: puerto de acceso, base de VLAN, modo del enlace y por último los detalles del troncal.'),
  ],
};
